AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Pushes RDS Enhanced metrics to Datadog.
Resources:
  rdslambdaddfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: Pushes RDS Enhanced metrics to Datadog.
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          kmsEncryptedKeys: YOUR_KEY
